name: Terraform CI/CD

on:
  workflow_dispatch:  # Allows manual triggering of the pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./dev  # Update this if your main.tf is in a different location

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./dev

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve
        working-directory: ./dev

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
