name: Terraform CI Pipeline

on:
  push:
    branches:
      - dev  # Run this workflow on pushes to the dev branch

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 4.1.0

      - name: Initialize Terraform
        working-directory: ./dev
        run: terraform init

      - name: Apply Terraform Plan
        working-directory: ./dev
        run: terraform apply -auto-approve

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
