name: Terraform CI/CD

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Allows you to manually run the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./dev

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve
        working-directory: ./dev
